version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: commerce-frontend
    restart: unless-stopped
    ports:
      - "80:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://13.51.200.74:8080/api/v1
    networks:
      - commerce-network

networks:
  commerce-network:
    driver: bridge